-- Create the reservations table
CREATE TABLE reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read reservations
CREATE POLICY "Allow public read" ON reservations
  FOR SELECT USING (true);

-- Allow anyone to insert reservations
CREATE POLICY "Allow public insert" ON reservations
  FOR INSERT WITH CHECK (true);

-- Create index for faster lookups by number
CREATE INDEX idx_reservations_number ON reservations (number);
